# Generated by Django 3.1.4 on 2021-01-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.TextField(max_length=50)),
                ('board', models.TextField(max_length=50)),
                ('degree', models.TextField(max_length=50)),
                ('startingdate', models.DateField()),
                ('endingdate', models.DateField()),
                ('result', models.TextField(max_length=10)),
                ('percentage', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.TextField(max_length=20)),
                ('previousDesignation', models.TextField(max_length=20)),
                ('startingDate', models.DateField()),
                ('endingDate', models.DateField()),
                ('responsibilities', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fname', models.TextField(max_length=50)),
                ('CNIC', models.IntegerField(max_length=11)),
                ('age', models.IntegerField(max_length=5)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('education', models.ManyToManyField(default=None, to='employee.EmployeeEducation')),
                ('experience', models.ManyToManyField(default=None, to='employee.EmployeeExperience')),
                ('skills', models.ManyToManyField(default=None, to='employee.EmployeeSkills')),
            ],
        ),
    ]
