# Generated by Django 3.1.4 on 2021-03-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave',
            field=models.IntegerField(default=None),
        ),
    ]
