# Generated by Django 3.1.4 on 2021-03-26 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employeesalarycalculations_salarysheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalarycalculations',
            name='emp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
