# Generated by Django 3.1.4 on 2021-03-26 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20210326_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalarycalculations',
            name='emp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
