# Generated by Django 3.1.4 on 2021-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_auto_20210326_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalarycalculations',
            name='leaveDeduction',
            field=models.IntegerField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='employeesalarycalculations',
            name='total',
            field=models.TextField(blank=True, default=None, max_length=10),
        ),
    ]
