# Generated by Django 3.1.4 on 2021-03-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_auto_20210326_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalarycalculations',
            name='addition',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeesalarycalculations',
            name='deducation',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeesalarycalculations',
            name='leaveDeduction',
            field=models.IntegerField(max_length=51),
        ),
        migrations.AlterField(
            model_name='employeesalarycalculations',
            name='leaves',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeesalarycalculations',
            name='total',
            field=models.IntegerField(max_length=50),
        ),
    ]
