# Generated by Django 3.1.4 on 2021-03-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20210326_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalarycalculations',
            name='addition',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='employeesalarycalculations',
            name='deducation',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='employeesalarycalculations',
            name='leaves',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
