# Generated by Django 3.1.4 on 2021-05-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.TextField(blank=True, default=None, max_length=20)),
                ('bug_title', models.TextField(blank=True, default=None, max_length=20)),
                ('bug_description', models.TextField(blank=True, default=None, max_length=200)),
            ],
        ),
    ]
