# Generated by Django 3.1.4 on 2021-05-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='bug_pic',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
