# Generated by Django 3.1.4 on 2021-05-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_bugs_bug_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugs',
            name='project_title',
        ),
    ]
