# Generated by Django 3.1.4 on 2021-05-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20210526_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='bug_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
