# Generated by Django 3.1.4 on 2020-12-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='requirement',
            field=models.ManyToManyField(default=None, to='dashboard.Requirement'),
        ),
    ]
