# Generated by Django 3.1.4 on 2020-12-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201228_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='status',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
