# Generated by Django 3.1.4 on 2021-05-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_bugs_bug_pic'),
        ('dashboard', '0004_requirement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='bugs',
            field=models.ManyToManyField(default=None, to='testing.Bugs'),
        ),
    ]
